import type { RoleplayScenario } from '../../types/roleplay.js';

export const ROLEPLAY_SCENARIOS: RoleplayScenario[] = [
  {
    id: 'cafe_ordering',
    category: 'daily',
    difficulty: 'beginner',
    estimatedMinutes: 5,
    titleKey: 'roleplay.scenario.cafe.title',
    descriptionKey: 'roleplay.scenario.cafe.description',
    userRoleKey: 'roleplay.scenario.cafe.userRole',
    aiRoleKey: 'roleplay.scenario.cafe.aiRole',
    goalIds: ['daily_conversation', 'travel'],
    supportedFocusAreas: ['fluency', 'pronunciation'],
    premium: false,
    objective: 'Place an order and respond to at least one relevant follow-up question.',
  },
  {
    id: 'airport_checkin',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 6,
    titleKey: 'roleplay.scenario.airport.title',
    descriptionKey: 'roleplay.scenario.airport.description',
    userRoleKey: 'roleplay.scenario.airport.userRole',
    aiRoleKey: 'roleplay.scenario.airport.aiRole',
    goalIds: ['travel'],
    supportedFocusAreas: ['fluency', 'completeness'],
    premium: false,
    objective: 'Complete the check-in interaction by providing relevant travel details.',
  },
  {
    id: 'hotel_checkin',
    category: 'travel',
    difficulty: 'intermediate',
    estimatedMinutes: 6,
    titleKey: 'roleplay.scenario.hotel.title',
    descriptionKey: 'roleplay.scenario.hotel.description',
    userRoleKey: 'roleplay.scenario.hotel.userRole',
    aiRoleKey: 'roleplay.scenario.hotel.aiRole',
    goalIds: ['travel'],
    supportedFocusAreas: ['fluency', 'pronunciation'],
    premium: true,
    objective: 'Complete a hotel check-in and respond to a practical follow-up.',
  },
  {
    id: 'asking_directions',
    category: 'travel',
    difficulty: 'beginner',
    estimatedMinutes: 5,
    titleKey: 'roleplay.scenario.directions.title',
    descriptionKey: 'roleplay.scenario.directions.description',
    userRoleKey: 'roleplay.scenario.directions.userRole',
    aiRoleKey: 'roleplay.scenario.directions.aiRole',
    goalIds: ['travel', 'daily_conversation'],
    supportedFocusAreas: ['fluency', 'completeness'],
    premium: false,
    objective: 'Ask for directions and acknowledge or clarify the directions received.',
  },
  {
    id: 'small_talk',
    category: 'social',
    difficulty: 'beginner',
    estimatedMinutes: 5,
    titleKey: 'roleplay.scenario.smallTalk.title',
    descriptionKey: 'roleplay.scenario.smallTalk.description',
    userRoleKey: 'roleplay.scenario.smallTalk.userRole',
    aiRoleKey: 'roleplay.scenario.smallTalk.aiRole',
    goalIds: ['daily_conversation', 'fluency'],
    supportedFocusAreas: ['fluency', 'pronunciation'],
    premium: false,
    objective: 'Exchange relevant small talk and keep the conversation moving.',
  },
  {
    id: 'job_interview',
    category: 'work',
    difficulty: 'advanced',
    estimatedMinutes: 8,
    titleKey: 'roleplay.scenario.interview.title',
    descriptionKey: 'roleplay.scenario.interview.description',
    userRoleKey: 'roleplay.scenario.interview.userRole',
    aiRoleKey: 'roleplay.scenario.interview.aiRole',
    goalIds: ['job_interview', 'work'],
    supportedFocusAreas: ['fluency', 'pronunciation', 'completeness'],
    premium: true,
    objective: 'Answer core interview prompts with relevant, meaningful information.',
  },
  {
    id: 'work_meeting',
    category: 'work',
    difficulty: 'intermediate',
    estimatedMinutes: 7,
    titleKey: 'roleplay.scenario.meeting.title',
    descriptionKey: 'roleplay.scenario.meeting.description',
    userRoleKey: 'roleplay.scenario.meeting.userRole',
    aiRoleKey: 'roleplay.scenario.meeting.aiRole',
    goalIds: ['work', 'daily_conversation'],
    supportedFocusAreas: ['fluency', 'completeness'],
    premium: true,
    objective: 'Share a useful work update and respond to a relevant meeting question.',
  },
  {
    id: 'shopping_return',
    category: 'daily',
    difficulty: 'intermediate',
    estimatedMinutes: 6,
    titleKey: 'roleplay.scenario.shopping.title',
    descriptionKey: 'roleplay.scenario.shopping.description',
    userRoleKey: 'roleplay.scenario.shopping.userRole',
    aiRoleKey: 'roleplay.scenario.shopping.aiRole',
    goalIds: ['daily_conversation'],
    supportedFocusAreas: ['fluency', 'pronunciation'],
    premium: false,
    objective: 'Explain the return request and respond to the store associate’s follow-up.',
  },
];

export function getRoleplayScenarioById(scenarioId: string): RoleplayScenario | null {
  return ROLEPLAY_SCENARIOS.find((scenario) => scenario.id === scenarioId) ?? null;
}
